AllCops:
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes:
    - bin/**
    - config/**
    - db/**
    - script/**
    - vendor/**
  RunRailsCops: true

AlignParameters:
  Enabled: false
