language: ruby

addons:
  postgresql: 9.3

rvm:
  - 2.1.0

before_script:
  - psql --version
  - cp .env.travis .env
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database deploytower_test;' -U postgres
